services:
  glvd-postgres:
    build:
      dockerfile: Containerfile
      args:
        container_variant: sampledata
    hostname: glvd-postgres
    environment:
      POSTGRES_USER: glvd
      POSTGRES_DB: glvd
      POSTGRES_PASSWORD: glvd
    ports:
      - "5432:5432"
